# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool:
  name: 'Default'  # Replace with your self-hosted pool name

steps:
- task: TerraformCLI@0
  displayName: Terraform Init
  inputs:
    command: 'init'
    allowTelemetryCollection: true

- task: TerraformCLI@0
  displayName: Terraform Plan
  inputs:
    command: 'plan'
    environmentServiceName: 'tf_Identity'
    allowTelemetryCollection: false

- task: TerraformCLI@0
  displayName: Terraform Apply
  inputs:
    command: 'apply'
    environmentServiceName: 'tf_Identity'
    allowTelemetryCollection: true


